logging: "DEBUG" # in ["INFO", "DEBUG", "WARNING"]
runs: 2
horizon: 10
episodes: 3
gamma: 0.95
num_sims: 512
exploration: 1
# rollout_policy: "" # ["", "default", "gridverse-extra"]  # NYI
search_depth: 0
pouct_evaluation: "inverted_goal_distance"  # in ["", "inverted_goal_distance"]
belief: rejection_sampling # in ["rejection_sampling", "importance_sampling"]
num_particles: 512
belief_minimal_sample_size: 0 # in ["on_true", "on_prior"]
# train_offline: "on_true"  # NYI
prior_option: "" # in ["", "noise_turn_orientation"]
optimizer: "SGD" # in ["SGD", "Adam"]
learning_rate: .001
online_learning_rate: .0001
network_size: 32
num_nets: 1
batch_size: 32
num_pretrain_epochs: 1024
use_gpu: False
random_seed: 0
tensorboard_logdir: ""
# perturb_stdev: 0
# backprop: True
dropout_rate: 0
# replay_update: True
# save_path: /tmp/some/folder
